platform :ios, '6.0'

xcodeproj 'EHObjectSyncManager Example'

pod 'PonyDebugger',       '0.2.1beta1'
pod 'A2DynamicDelegate',  '~> 2.0.2'

# Monospace Pods
# pod 'MSTableKit',             :git => 'https://github.com/monospacecollective/MSTableKit.git', :branch => 'development'
pod 'UIControl-BlockAction',  :git => 'https://github.com/monospacecollective/UIControl-BlockAction.git'
pod 'UIView-Autolayout',      :git => 'https://github.com/eric-horacek/UIView-Autolayout'

# Local
pod 'EHObjectSyncManager',  :local => '../../'
pod 'MSTableKit',           :local => '~/Development/MSTableKit'
