platform :ios, '6.0'

xcodeproj 'EHObjectSyncManager Example'

pod 'EHObjectSyncManager',  :path => '../../'
pod 'PonyDebugger',         '0.2.1beta1'
pod 'BlocksKit',            '~> 1.8.2'

# Monospace Pods
# pod 'MSTableKit',             :git => 'https://github.com/monospacecollective/MSTableKit.git', :branch => 'development'
pod 'UIView-Autolayout',      :git => 'https://github.com/eric-horacek/UIView-Autolayout'

# Local
pod 'MSTableKit',           :path => '~/Development/MSTableKit'
